[workspace]
members = [
  "rustler",
  "rustler_codegen",
  "rustler_sys",
  "rustler_tests/native/binary_example",
  "rustler_tests/native/rustler_test",
  "rustler_tests/native/deprecated_macros",
]
