[package]
name = "deprecated_macros"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "deprecated_macros"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { path = "../../../rustler" }
